### ISSUE TITLE
Crash when loading VP9 source

### ISSUE THREAD

**Issue by SirJMD** [stax76/staxrip#137]
Upon loading a mkv-source containing a VP9 video, Staxrip crashes. I've tried a few other VP9 sources, which have worked with no issues, other than the FPS being detected improperly.

Any ideas on how to fix this?

`-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                 Error Index with ffmsindex
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

Index with ffmsindex failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

Indexing error: Invalid initial pts, dts, and duration

Start:    19:18:17
End:      19:18:17
Duration: 00:00:00

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                         Exception
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

StaxRip.ErrorAbortException: Index with ffmsindex failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

Indexing error: Invalid initial pts, dts, and duration

   at StaxRip.Proc.Start() in D:\Projekte\VS\VB\StaxRip\General\Proc.vb:line 240
   at StaxRip.GlobalClass.ffmsindex(String sourcePath, String cachePath, Boolean indexAudio, Boolean noLog) in D:\Projekte\VS\VB\StaxRip\General\Misc.vb:line 410
   at StaxRip.MainForm.Indexing() in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 2908
   at StaxRip.VideoScript.Synchronize(Boolean convertToRGB, Boolean comparePath) in D:\Projekte\VS\VB\StaxRip\General\VideoScript.vb:line 191
   at StaxRip.VideoScript.GetFramerate() in D:\Projekte\VS\VB\StaxRip\General\VideoScript.vb:line 302
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isNotEncoding) in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 1798`

**Comment by stax76** [comment]
You can try to report it here:

https://github.com/FFMS/ffms2/issues

As alternative you can try to right-click the source filter and choose LWLibavVideoSource before you open your source. If it also fails you can try to report it here:

https://github.com/VFR-maniac/L-SMASH-Works/issues
