### ISSUE TITLE
Out of memory in batch processing

### ISSUE THREAD

**Issue by Zcehtro** [stax76/staxrip#175]
When choosing source file and file batch, I added aproximately 500 files to the batch. It reached a certain point in creating the .srip files and then StaxRip crashed.

It produced a Log.txt. Here it is:

[Log.txt](https://github.com/stax76/staxrip/files/1009778/Log.txt)

I think it says that it ran out of memory.

**Comment by stax76** [comment]
I'm aware of the problem, in my last test each job added about 50 MB that don't get freed, since the app is large with many features and much complexity it will probably be very difficult to fix, I tried one time to improve it but failed, I have to try much harder.

**Comment by Zcehtro** [comment]
I wouldn't give it a high priority, batch processing that many files is very unlikely.

I think the exact moment it crashes is after it creates all the .srip files and it begins to populate the jobs list. At that moment StaxRip freezes.

**Comment by stax76** [comment]
Did it happen by just adding to the job list or while executing the jobs? I added 100 jobs which hardly took memory, since the last build runs only one job per instance running the job list should also be no problem.

**Comment by Zcehtro** [comment]
Could you try with a larger number?

I'd need some time to look for 500 more videos to add to the job list.

**Comment by Zcehtro** [comment]
Just tried it again, here's the log file:

```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
      _________ __                __________.__        
     /   _____//  |______  ___  __\______   \__|_____  
     \_____  \\   __\__  \ \  \/  /|       _/  \____ \ 
     /        \|  |  / __ \_>    < |    |   \  |  |_> >
    /_______  /|__| (____  /__/\_ \|____|_  /__|   __/ 
            \/           \/      \/       \/   |__|   

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                        Environment
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

StaxRip x64 : 1.4.5.3
OS          : Windows 10 Education 1607
Language    : English (United States)
CPU         : Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
GPU         : NVIDIA GeForce GTX 1070

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                         Exception
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

System.OutOfMemoryException: Out of memory.
   at System.Drawing.Graphics.FromHdcInternal(IntPtr hdc)
   at System.Drawing.Font.ToLogFont(Object logFont)
   at System.Drawing.Font.ToHfont()
   at System.Windows.Forms.Control.FontHandleWrapper..ctor(Font font)
   at System.Windows.Forms.Control.get_FontHandle()
   at System.Windows.Forms.Control.get_FontHandle()
   at System.Windows.Forms.Control.get_FontHandle()
   at System.Windows.Forms.Control.SetWindowFont()
   at System.Windows.Forms.Control.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.ListView.OnHandleCreated(EventArgs e)
   at StaxRip.UI.ListViewEx.OnHandleCreated(EventArgs e) in D:\Projekte\VS\VB\StaxRip\UI\Controls\ListViewEx.vb:line 410
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at StaxRip.UI.ListViewEx.WndProc(Message& m) in D:\Projekte\VS\VB\StaxRip\UI\Controls\ListViewEx.vb:line 224
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

**Comment by stax76** [comment]
I'm able to reproduce it, the extended ListView control crashes, since such large job numbers aren't common and it would be very difficult to fix I leave this unresolved.
