### ISSUE TITLE
wondering if theres a complete guide on this

### ISSUE THREAD

**Issue by aussiebro** [stax76/staxrip#199]
all the guides i been looking up dont help me with all the settings. and how to use the apps that are within this.

**Comment by aussiebro** [comment]
the guides i saw were for outdated versions of this with settings in different spots and some not there to

**Comment by aussiebro** [comment]
how do i get compressability check to work. it says down bottom press here to do it and i press down bottom and nothing happens lol. im using nvidia x265 profile

**Comment by aussiebro** [comment]
also whats this mean i tried to do video comparison and the 1st video i opend gave a error 





TargetInvocationException

Exception has been thrown by the target of an invocation.

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> StaxRip.ErrorAbortException: Index with ffmsindex failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

Writing index... Error writing index: Failed to open 'T:\TV shows\Workaholics\Season 2\Workaholics - 2x02 - Dry Guys_temp\Workaholics - 2x02 - Dry Guys.ffindex'


   at StaxRip.Proc.Start() in D:\Projekte\VS\VB\StaxRip\General\Proc.vb:line 221
   at StaxRip.GlobalClass.ffmsindex(String sourcePath, String cachePath, Boolean indexAudio, Boolean noLog) in D:\Projekte\VS\VB\StaxRip\General\GlobalClass.vb:line 494
   at StaxRip.MainForm.Indexing() in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 2909
   at StaxRip.VideoScript.Synchronize(Boolean convertToRGB, Boolean comparePath) in D:\Projekte\VS\VB\StaxRip\General\VideoScript.vb:line 189
   at StaxRip.VideoComparisonForm.VideoTab.Open(String sourePath) in D:\Projekte\VS\VB\StaxRip\Forms\VideoComparisonForm.vb:line 276
   at StaxRip.VideoComparisonForm.Add(String sourePath) in D:\Projekte\VS\VB\StaxRip\Forms\VideoComparisonForm.vb:line 86
   at StaxRip.VideoComparisonForm.Add() in D:\Projekte\VS\VB\StaxRip\Forms\VideoComparisonForm.vb:line 56
   at StaxRip.MainForm.ShowVideoComparison() in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 3502
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at StaxRip.CommandManager.Process(Command command, List`1 params) in D:\Projekte\VS\VB\StaxRip\General\General.vb:line 1231
   at StaxRip.CommandManager.Process(String name, List`1 params) in D:\Projekte\VS\VB\StaxRip\General\General.vb:line 1222
   at StaxRip.UI.CustomMenu.Process(CustomMenuItem item) in D:\Projekte\VS\VB\StaxRip\UI\Menu Types.vb:line 250
   at StaxRip.UI.CustomMenu.OnCommand(CustomMenuItem item) in D:\Projekte\VS\VB\StaxRip\UI\Menu Types.vb:line 243
   at StaxRip.UI.CustomMenu.MenuClick(Object sender, EventArgs e) in D:\Projekte\VS\VB\StaxRip\UI\Menu Types.vb:line 235
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at StaxRip.UI.MenuItemEx.OnClick(EventArgs e) in D:\Projekte\VS\VB\StaxRip\UI\Menu Types.vb:line 456
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by stax76** [comment]
If there is a guide then not from me. Make a screenshot and post the log file to pastebin with auto expire or better use crf instead of 2pass.

**Comment by aussiebro** [comment]
![error](https://user-images.githubusercontent.com/29494197/27264879-c9389298-54cc-11e7-8147-3564bf76a561.jpg)
https://pastebin.com/F1u86euy

here you go. i have no clue what auto expire is. i think im using 2pass. is that vbrHQ?

**Comment by stax76** [comment]
Try the last test build using only the default values for nvenc.

nvenc don't has a real 2pass mode.

pastebin has a option to delete the document after 30 days.

https://github.com/stax76/staxrip/blob/master/md/test-build.md

**Comment by aussiebro** [comment]
was i ment to select

**Comment by aussiebro** [comment]
was decoder ment to be left as avisynth with nvidia h265 option?   it gave me laggy video. and i tried avcuvid cuda and thats giving me this message https://pastebin.com/Ri0uuKYV
