### ISSUE TITLE
Crashes when adding hundreds of files (~1200)

### ISSUE THREAD

**Issue by SEVEZ** [stax76/staxrip#219]
The problem occurs when I try to add about 1200 files into batch processing window. It's ok if I add the by smaller portions (<200). Here's the exception I get:

System.OutOfMemoryException: Out of memory.
   at System.Drawing.Graphics.FromHdcInternal(IntPtr hdc)
   at System.Drawing.Font.ToLogFont(Object logFont)
   at System.Drawing.Font.ToHfont()
   at System.Windows.Forms.Control.FontHandleWrapper..ctor(Font font)
   at System.Windows.Forms.Control.get_FontHandle()
   at System.Windows.Forms.Control.get_FontHandle()
   at System.Windows.Forms.Control.get_FontHandle()
   at System.Windows.Forms.Control.SetWindowFont()
   at System.Windows.Forms.Control.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.ListView.OnHandleCreated(EventArgs e)
   at StaxRip.UI.ListViewEx.OnHandleCreated(EventArgs e) in D:\Projekte\VS\VB\StaxRip\UI\Controls\ListViewEx.vb:line 410
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at StaxRip.UI.ListViewEx.WndProc(Message& m) in D:\Projekte\VS\VB\StaxRip\UI\Controls\ListViewEx.vb:line 224
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by stax76** [comment]
It's a bit difficult to fix, is it a important use case for you?

Duplicate of #175

**Comment by SEVEZ** [comment]
Yes, it's pretty critical. I have my personal collection of video tutorials - about 3500 hrs of video and it's many thousands of files. And because of this issue I can't just point on some heavy folder and wait until encoding ends (time doesn't matter). I have to add into the queue every 2-3 hrs manually. Admittedly it's not a huge automation ) I'm using nvidia hevc which encodes very fast - so the queue gets empty in 2-3 hrs too. So it would very-very awesome if you could fix this issue. I find this piece of software very handy and cool, but this lil annoying issue hurts too much =)

**Comment by stax76** [comment]
It's probably not easy to overcome, on a test form I tried to add 1000 items to the listview that crashed, it was fine, the problem is probably not the list view directly but too many os resources used before the listview is used, last time I worked on the problem there was another strange resource related com+ error. With the newest built 1527 it should be possible as workaround to use the CLI to add the jobs.

**Comment by SEVEZ** [comment]
I managed to make one trick with it. I discovered, that crash happens when I try to add many hundreds of files at once via batch directory. But actually I can add by ~400-500 items through batch and it woks fine. Then these 400-500 items are added to the job list which doesn't fail. Then I can add 400-500 items again and so on. Eventually there will be exactly the same thousands of files in jobs list, but without any flaws during adding items. I think as a temporary workaround you could break the list of many hundreds of files into smaller segments and add them to job list one by one.

**Comment by stax76** [comment]
There were some issues solved regarding job processing:

https://github.com/stax76/staxrip/blob/master/md/test-build.md
