### ISSUE TITLE
bulk processing errors

### ISSUE THREAD

**Issue by amccool** [stax76/staxrip#23]
System.ArgumentException: TimeSpan does not accept floating point Not-a-Number values.
   at System.TimeSpan.Interval(Double value, Int32 scale)
   at StaxRip.MainForm.Encode() in D:\Projekte\GitHub\staxrip\Forms\MainForm.vb:line 2299
   at StaxRip.MainForm.RunJobRecursive() in D:\Projekte\GitHub\staxrip\Forms\MainForm.vb:line 3605

**Comment by stax76** [comment]
I fixed this particular crash but it can only happen when something went wrong before I think.
