### ISSUE TITLE
Error while encoding

### ISSUE THREAD

**Issue by el3wdy** [stax76/staxrip#233]
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
      _________ __                __________.__        
     /   _____//  |______  ___  __\______   \__|_____  
     \_____  \\   __\__  \ \  \/  /|       _/  \____ \ 
     /        \|  |  / __ \_>    < |    |   \  |  |_> >
    /_______  /|__| (____  /__/\_ \|____|_  /__|   __/ 
            \/           \/      \/       \/   |__|   

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                        Environment
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

StaxRip    : 1.5.0.0
Windows    : Windows Server 2012 Standard
Language   : English (United States)
CPU        : Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
GPU        : Intel(R) HD Graphics 4000
Resolution : 1920 x 1080
DPI        : 96

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                   Source file MediaInfo
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

C:\Users\Administrator\Documents\Camtasia Studio\ppp\ppp.avi

General
Complete name                : C:\Users\Administrator\Documents\Camtasia Studio\ppp\ppp.avi
Format                       : AVI
Format/Info                  : Audio Video Interleave
Format profile               : OpenDML
File size                    : 13.7 GiB
Duration                     : 1 h 59 min
Overall bit rate             : 16.4 Mb/s

Video
ID                           : 0
Format                       : tsc2
Codec ID                     : tsc2
Duration                     : 1 h 59 min
Bit rate                     : 16.0 Mb/s
Width                        : 1 280 pixels
Height                       : 544 pixels
Display aspect ratio         : 2.35:1
Frame rate                   : 24.000 FPS
Bits/(Pixel*Frame)           : 0.955
Stream size                  : 13.4 GiB (97%)

Audio
ID                           : 1
Format                       : PCM
Format settings, Endianness  : Little
Format settings, Sign        : Signed
Codec ID                     : 1
Duration                     : 1 h 59 min
Bit rate mode                : Constant
Bit rate                     : 352.8 kb/s
Channel(s)                   : 1 channel
Sampling rate                : 22.05 kHz
Bit depth                    : 16 bits
Stream size                  : 303 MiB (2%)
Alignment                    : Aligned on interleaves
Interleave, duration         : 33  ms (0.80 video frame)
Interleave, preload duration : 366  ms

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
             Demux audio using ffmpeg 3.2.2 x64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

C:\Users\Administrator\Desktop\StaxRip-x64-1.5.0.0\Apps\ffmpeg\ffmpeg.exe -i "C:\Users\Administrator\Documents\Camtasia Studio\ppp\ppp.avi" -vn -sn -y -hide_banner -c:a pcm_s16le "C:\Users\Administrator\Documents\Camtasia Studio\ppp\ppp_temp\ppp ID2.wav"

Guessed Channel Layout for Input Stream #0.1 : mono
Input #0, avi, from 'C:\Users\Administrator\Documents\Camtasia Studio\ppp\ppp.avi':
Duration: 01:59:58.13, start: 0.000000, bitrate: 16384 kb/s
Stream #0:0: Video: tscc2 (tsc2 / 0x32637374), yuv444p, 1280x544, 15953 kb/s, 24 fps, 24 tbr, 24 tbn, 24 tbc
Stream #0:1: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 22050 Hz, mono, s16, 352 kb/s
Output #0, wav, to 'C:\Users\Administrator\Documents\Camtasia Studio\ppp\ppp_temp\ppp ID2.wav':
Metadata:
ISFT            : Lavf57.56.100
Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 22050 Hz, mono, s16, 352 kb/s
Metadata:
encoder         : Lavc57.64.101 pcm_s16le
Stream mapping:
Stream #0:1 -> #0:0 (pcm_s16le (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
size=    2000kB time=00:00:46.43 bitrate= 352.8kbits/s speed=92.8x
size=    2703kB time=00:01:02.76 bitrate= 352.8kbits/s speed=61.8x
size=    3679kB time=00:01:25.43 bitrate= 352.8kbits/s speed=55.9x
size=    4957kB time=00:01:55.10 bitrate= 352.8kbits/s speed=56.3x
size=    5962kB time=00:02:18.43 bitrate= 352.8kbits/s speed=54.3x
size=    6608kB time=00:02:33.43 bitrate= 352.8kbits/s speed=50.3x
size=    8144kB time=00:03:09.10 bitrate= 352.8kbits/s speed=  53x
size=    9910kB time=00:03:50.10 bitrate= 352.8kbits/s speed=56.5x
size=   10843kB time=00:04:11.76 bitrate= 352.8kbits/s speed=  55x
size=   12092kB time=00:04:40.76 bitrate= 352.8kbits/s speed=55.3x
size=   13254kB time=00:05:07.76 bitrate= 352.8kbits/s speed=52.7x
size=   13801kB time=00:05:20.46 bitrate= 352.8kbits/s speed=48.9x
size=   15322kB time=00:05:55.76 bitrate= 352.8kbits/s speed=50.4x
size=   16973kB time=00:06:34.10 bitrate= 352.8kbits/s speed=52.2x
size=   17662kB time=00:06:50.10 bitrate= 352.8kbits/s speed=50.7x
size=   19212kB time=00:07:26.10 bitrate= 352.8kbits/s speed=  52x
size=   21136kB time=00:08:10.76 bitrate= 352.8kbits/s speed=  54x
size=   22600kB time=00:08:44.76 bitrate= 352.8kbits/s speed=53.3x
size=   23633kB time=00:09:08.76 bitrate= 352.8kbits/s speed=  53x
size=   25227kB time=00:09:45.76 bitrate= 352.8kbits/s speed=  54x
size=   26964kB time=00:10:26.10 bitrate= 352.8kbits/s speed=55.1x
size=   28651kB time=00:11:05.26 bitrate= 352.8kbits/s speed=56.1x
size=   29849kB time=00:11:33.10 bitrate= 352.8kbits/s speed=55.6x
size=   31486kB time=00:12:11.10 bitrate= 352.8kbits/s speed=56.4x
size=   33338kB time=00:12:54.10 bitrate= 352.8kbits/s speed=57.5x
size=   35175kB time=00:13:36.76 bitrate= 352.8kbits/s speed=58.4x
size=   36309kB time=00:14:03.10 bitrate= 352.8kbits/s speed=58.2x
size=   37845kB time=00:14:38.76 bitrate= 352.8kbits/s speed=58.7x
size=   38678kB time=00:14:58.10 bitrate= 352.8kbits/s speed=56.9x
size=   39396kB time=00:15:14.76 bitrate= 352.8kbits/s speed=56.2x
size=   39597kB time=00:15:19.43 bitrate= 352.8kbits/s speed=54.7x
size=   39740kB time=00:15:22.76 bitrate= 352.8kbits/s speed=53.3x
size=   39812kB time=00:15:24.43 bitrate= 352.8kbits/s speed=51.2x
size=   39898kB time=00:15:26.43 bitrate= 352.8kbits/s speed=49.8x
size=   40042kB time=00:15:29.76 bitrate= 352.8kbits/s speed=48.6x
size=   40327kB time=00:15:36.40 bitrate= 352.8kbits/s speed=47.7x
size=   40559kB time=00:15:41.76 bitrate= 352.8kbits/s speed=46.7x
size=   40659kB time=00:15:44.10 bitrate= 352.8kbits/s speed=45.4x
size=   40774kB time=00:15:46.76 bitrate= 352.8kbits/s speed=44.4x
size=   41018kB time=00:15:52.43 bitrate= 352.8kbits/s speed=43.7x
size=   41305kB time=00:15:59.10 bitrate= 352.8kbits/s speed=42.9x
size=   41406kB time=00:16:01.43 bitrate= 352.8kbits/s speed=42.1x
size=   41879kB time=00:16:12.43 bitrate= 352.8kbits/s speed=41.6x
size=   42037kB time=00:16:16.10 bitrate= 352.8kbits/s speed=40.9x
size=   42123kB time=00:16:18.10 bitrate= 352.8kbits/s speed=39.7x
size=   42209kB time=00:16:20.10 bitrate= 352.8kbits/s speed=  39x
size=   42310kB time=00:16:22.43 bitrate= 352.8kbits/s speed=38.2x
size=   42420kB time=00:16:25.00 bitrate= 352.8kbits/s speed=37.6x
size=   42537kB time=00:16:27.70 bitrate= 352.8kbits/s speed=36.9x
size=   42626kB time=00:16:29.76 bitrate= 352.8kbits/s speed=36.3x
size=   42855kB time=00:16:35.10 bitrate= 352.8kbits/s speed=35.8x
size=   43114kB time=00:16:41.10 bitrate= 352.8kbits/s speed=35.4x
size=   43300kB time=00:16:45.43 bitrate= 352.8kbits/s speed=34.9x
size=   43573kB time=00:16:51.76 bitrate= 352.8kbits/s speed=34.5x
size=   43817kB time=00:16:57.43 bitrate= 352.8kbits/s speed=34.1x
size=   43875kB time=00:16:58.76 bitrate= 352.8kbits/s speed=33.5x
size=   44090kB time=00:17:03.76 bitrate= 352.8kbits/s speed=33.1x
size=   44406kB time=00:17:11.10 bitrate= 352.8kbits/s speed=32.8x
size=   44808kB time=00:17:20.43 bitrate= 352.8kbits/s speed=32.5x
size=   45095kB time=00:17:27.10 bitrate= 352.8kbits/s speed=32.2x
size=   45224kB time=00:17:30.10 bitrate= 352.8kbits/s speed=31.8x
size=   45425kB time=00:17:34.76 bitrate= 352.8kbits/s speed=31.5x
size=   45612kB time=00:17:39.10 bitrate= 352.8kbits/s speed=31.1x
size=   45712kB time=00:17:41.43 bitrate= 352.8kbits/s speed=30.7x
size=   45827kB time=00:17:44.10 bitrate= 352.8kbits/s speed=30.3x
size=   45956kB time=00:17:47.10 bitrate= 352.8kbits/s speed=29.9x
size=   46157kB time=00:17:51.76 bitrate= 352.8kbits/s speed=29.5x
size=   46329kB time=00:17:55.76 bitrate= 352.8kbits/s speed=29.2x
size=   47026kB time=00:18:11.93 bitrate= 352.8kbits/s speed=29.3x
size=   47435kB time=00:18:21.43 bitrate= 352.8kbits/s speed=29.1x
size=   47794kB time=00:18:29.76 bitrate= 352.8kbits/s speed=28.8x
size=   47866kB time=00:18:31.43 bitrate= 352.8kbits/s speed=28.5x
size=   48110kB time=00:18:37.10 bitrate= 352.8kbits/s speed=28.3x
size=   48440kB time=00:18:44.76 bitrate= 352.8kbits/s speed=28.1x
size=   48598kB time=00:18:48.43 bitrate= 352.8kbits/s speed=27.8x
size=   48899kB time=00:18:55.43 bitrate= 352.8kbits/s speed=27.7x
size=   49158kB time=00:19:01.43 bitrate= 352.8kbits/s speed=27.5x
size=   49488kB time=00:19:09.10 bitrate= 352.8kbits/s speed=27.3x
size=   50062kB time=00:19:22.43 bitrate= 352.8kbits/s speed=27.3x
size=   50823kB time=00:19:40.10 bitrate= 352.8kbits/s speed=27.4x
size=   51354kB time=00:19:52.43 bitrate= 352.8kbits/s speed=27.4x
size=   51885kB time=00:20:04.76 bitrate= 352.8kbits/s speed=27.3x
size=   52775kB time=00:20:25.43 bitrate= 352.8kbits/s speed=27.5x
size=   52890kB time=00:20:28.10 bitrate= 352.8kbits/s speed=27.2x
size=   53048kB time=00:20:31.76 bitrate= 352.8kbits/s speed=  27x
size=   53173kB time=00:20:34.66 bitrate= 352.8kbits/s speed=26.8x
size=   53263kB time=00:20:36.76 bitrate= 352.8kbits/s speed=26.5x
size=   53378kB time=00:20:39.43 bitrate= 352.8kbits/s speed=26.3x
size=   53522kB time=00:20:42.76 bitrate= 352.8kbits/s speed=26.1x
size=   53651kB time=00:20:45.76 bitrate= 352.8kbits/s speed=25.9x
size=   53823kB time=00:20:49.76 bitrate= 352.8kbits/s speed=25.7x
size=   53981kB time=00:20:53.43 bitrate= 352.8kbits/s speed=25.5x
size=   54282kB time=00:21:00.43 bitrate= 352.8kbits/s speed=25.3x
size=   54483kB time=00:21:05.10 bitrate= 352.8kbits/s speed=25.1x
size=   54656kB time=00:21:09.10 bitrate= 352.8kbits/s speed=  25x
size=   54885kB time=00:21:14.43 bitrate= 352.8kbits/s speed=24.8x
size=   55058kB time=00:21:18.43 bitrate= 352.8kbits/s speed=24.7x
size=   55574kB time=00:21:30.43 bitrate= 352.8kbits/s speed=24.6x
size=   56953kB time=00:22:02.43 bitrate= 352.8kbits/s speed=  25x
size=   58158kB time=00:22:30.43 bitrate= 352.8kbits/s speed=25.3x
size=   58415kB time=00:22:36.40 bitrate= 352.8kbits/s speed=25.2x
size=   58690kB time=00:22:42.76 bitrate= 352.8kbits/s speed=  25x
size=   58790kB time=00:22:45.10 bitrate= 352.8kbits/s speed=24.8x
size=   58977kB time=00:22:49.43 bitrate= 352.8kbits/s speed=24.6x
size=   59163kB time=00:22:53.76 bitrate= 352.8kbits/s speed=24.5x
size=   59321kB time=00:22:57.43 bitrate= 352.8kbits/s speed=24.3x
size=   59508kB time=00:23:01.76 bitrate= 352.8kbits/s speed=24.1x
size=   59737kB time=00:23:07.10 bitrate= 352.8kbits/s speed=  24x
size=   60039kB time=00:23:14.10 bitrate= 352.8kbits/s speed=23.9x
size=   60757kB time=00:23:30.76 bitrate= 352.8kbits/s speed=  24x
size=   61503kB time=00:23:48.10 bitrate= 352.8kbits/s speed=  24x
size=   61848kB time=00:23:56.10 bitrate= 352.8kbits/s speed=  24x
size=   62250kB time=00:24:05.43 bitrate= 352.8kbits/s speed=23.9x
size=   62321kB time=00:24:07.10 bitrate= 352.8kbits/s speed=23.7x
size=   62451kB time=00:24:10.10 bitrate= 352.8kbits/s speed=23.6x
size=   62566kB time=00:24:12.76 bitrate= 352.8kbits/s speed=23.4x
size=   62752kB time=00:24:17.10 bitrate= 352.8kbits/s speed=23.3x
size=   62996kB time=00:24:22.76 bitrate= 352.8kbits/s speed=23.2x
size=   64021kB time=00:24:46.56 bitrate= 352.8kbits/s speed=23.4x
size=   65350kB time=00:25:17.43 bitrate= 352.8kbits/s speed=23.7x
size=   66696kB time=00:25:48.66 bitrate= 352.8kbits/s speed=  24x
size=   67619kB time=00:26:10.10 bitrate= 352.8kbits/s speed=  24x
size=   68006kB time=00:26:19.10 bitrate= 352.8kbits/s speed=  24x
size=   68322kB time=00:26:26.43 bitrate= 352.8kbits/s speed=23.9x
size=   68509kB time=00:26:30.76 bitrate= 352.8kbits/s speed=23.7x
size=   68566kB time=00:26:32.10 bitrate= 352.8kbits/s speed=23.5x
size=   68638kB time=00:26:33.76 bitrate= 352.8kbits/s speed=23.4x
size=   68868kB time=00:26:39.10 bitrate= 352.8kbits/s speed=23.3x
size=   69054kB time=00:26:43.43 bitrate= 352.8kbits/s speed=23.2x
size=   69470kB time=00:26:53.10 bitrate= 352.8kbits/s speed=23.1x
size=   69600kB time=00:26:56.10 bitrate= 352.8kbits/s speed=  23x
size=   70762kB time=00:27:23.10 bitrate= 352.8kbits/s speed=23.2x
size=   72003kB time=00:27:51.90 bitrate= 352.8kbits/s speed=23.4x
size=   73016kB time=00:28:15.43 bitrate= 352.8kbits/s speed=23.6x
size=   74423kB time=00:28:48.10 bitrate= 352.8kbits/s speed=23.8x
size=   75184kB time=00:29:05.76 bitrate= 352.8kbits/s speed=23.9x

Start:    12:23:32 PM
End:      12:26:34 PM
Duration: 00:03:02

General
Complete name               : C:\Users\Administrator\Documents\Camtasia Studio\ppp\ppp_temp\ppp ID2.wav
Format                      : Wave
File size                   : 303 MiB
Duration                    : 1 h 59 min
Overall bit rate mode       : Constant
Overall bit rate            : 353 kb/s
Writing application         : Lavf57.56.100

Audio
Format                      : PCM
Format settings, Endianness : Little
Format settings, Sign       : Signed
Codec ID                    : 1
Duration                    : 1 h 59 min
Bit rate mode               : Constant
Bit rate                    : 352.8 kb/s
Channel(s)                  : 1 channel
Sampling rate               : 22.05 kHz
Bit depth                   : 16 bits
Stream size                 : 303 MiB (100%)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                    Index with ffmsindex
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

C:\Users\Administrator\Desktop\StaxRip-x64-1.5.0.0\Apps\Plugins\both\ffms2\ffmsindex.exe "C:\Users\Administrator\Documents\Camtasia Studio\ppp\ppp.avi" "C:\Users\Administrator\Documents\Camtasia Studio\ppp\ppp_temp\ppp.ffindex"

Writing index... done.

Start:    12:26:35 PM
End:      12:29:24 PM
Duration: 00:02:49

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                           Script
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

LoadPlugin("C:\Users\Administrator\Desktop\StaxRip-x64-1.5.0.0\Apps\Plugins\both\ffms2\ffms2.dll")
LoadPlugin("C:\Users\Administrator\Desktop\StaxRip-x64-1.5.0.0\Apps\Plugins\both\VSFilterMod\VSFilterMod.dll")
FFVideoSource("C:\Users\Administrator\Documents\Camtasia Studio\ppp\ppp.avi", colorspace = "YV12", \
              cachefile = "C:\Users\Administrator\Documents\Camtasia Studio\ppp\ppp_temp\ppp.ffindex")
ConvertToYV12()
TextSubMod("C:\Users\Administrator\Downloads\Planet of the Apes (2001)\Planet.of.the.Apes.2001.720p.BrRip.x264.YIFY.srt")

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                     Script Properties
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

source frame count : 172755
source frame rate  : 24.000000
source duration    : 01:59:58.1250000
target frame count : 172755
target frame rate  : 24.000000
target duration    : 01:59:58.1250000

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                Audio Source File MediaInfo
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

General
Complete name               : C:\Users\Administrator\Documents\Camtasia Studio\ppp\ppp_temp\ppp ID2.wav
Format                      : Wave
File size                   : 303 MiB
Duration                    : 1 h 59 min
Overall bit rate mode       : Constant
Overall bit rate            : 353 kb/s
Writing application         : Lavf57.56.100

Audio
Format                      : PCM
Format settings, Endianness : Little
Format settings, Sign       : Signed
Codec ID                    : 1
Duration                    : 1 h 59 min
Bit rate mode               : Constant
Bit rate                    : 352.8 kb/s
Channel(s)                  : 1 channel
Sampling rate               : 22.05 kHz
Bit depth                   : 16 bits
Stream size                 : 303 MiB (100%)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
            Audio encoding using eac3to 3.31 x86
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

C:\Users\Administrator\Desktop\StaxRip-x64-1.5.0.0\Apps\eac3to\eac3to.exe "C:\Users\Administrator\Documents\Camtasia Studio\ppp\ppp_temp\ppp ID2.wav" "C:\Users\Administrator\Documents\Camtasia Studio\ppp\ppp_temp\ppp ID2_out1.m4a" -quality=0.35 -normalize -progressnumbers

WAV, 1.0 channels, 1:59:58, 16 bits, 353kbps, 22kHz
Reading WAV...
Writing WAV...
Creating file "C:\Users\Administrator\Documents\Camtasia Studio\ppp\ppp_temp\ppp ID2_out1.m4a.pass1.wav"...
The original audio track has a constant bit depth of 16 bits.
Starting 2nd pass...
Reading WAV...
Reducing depth from 64 to 32 bits...
Encoding AAC <0.35> with NeroAacEnc...
Applying -0.09dB gain...
The processed audio track has a constant bit depth of 32 bits.
eac3to processing took 1 minute, 16 seconds.
Done.

Start:    12:54:19 PM
End:      12:55:36 PM
Duration: 00:01:17

Video Bitrate: 999 -> 1085
General
Complete name         : C:\Users\Administrator\Documents\Camtasia Studio\ppp\ppp_temp\ppp ID2_out1.m4a
Format                : MPEG-4
Format profile        : Base Media / Version 2
Codec ID              : mp42 (M4A /mp42/isom)
File size             : 25.3 MiB
Duration              : 1 h 59 min
Overall bit rate mode : Variable
Overall bit rate      : 29.5 kb/s
Encoded date          : UTC 2017-07-22 09:54:23
Tagged date           : UTC 2017-07-22 09:55:35

Audio
ID                    : 1
Format                : AAC
Format/Info           : Advanced Audio Codec
Format profile        : LC
Codec ID              : 40
Duration              : 1 h 59 min
Bit rate mode         : Variable
Bit rate              : 28.7 kb/s
Maximum bit rate      : 40.7 kb/s
Channel(s)            : 1 channel
Channel positions     : Front: C
Sampling rate         : 22.05 kHz
Frame rate            : 21.533 FPS (1024 spf)
Compression mode      : Lossy
Stream size           : 24.7 MiB (98%)
Writing library       : Nero AAC codec 1.5.4.0
Encoded date          : UTC 2017-07-22 09:54:23
Tagged date           : UTC 2017-07-22 09:55:35

Menu

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
       Encoding video using x264 0.150.2833 8-Bit x64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

C:\Users\Administrator\Desktop\StaxRip-x64-1.5.0.0\Apps\x264\x264.exe --pass 1 --bitrate 1085 --stats "C:\Users\Administrator\Documents\Camtasia Studio\ppp\ppp_temp\ppp.stats" --output NUL "C:\Users\Administrator\Documents\Camtasia Studio\ppp\ppp_temp\ppp.avs"

avs [info]: 1280x544p 0:0 @ 24/1 fps (cfr)
x264 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
x264 [info]: profile Main, level 3.1
x264 [info]: frame I:1149  Avg QP:17.64  size: 45804
x264 [info]: frame P:50782 Avg QP:20.21  size: 11688
x264 [info]: frame B:120824 Avg QP:22.32  size:  2667
x264 [info]: consecutive B-frames:  3.9%  5.9%  8.0% 82.3%
x264 [info]: mb I  I16..4: 35.6%  0.0% 64.4%
x264 [info]: mb P  I16..4: 38.3%  0.0%  0.0%  P16..4: 36.9%  0.0%  0.0%  0.0%  0.0%    skip:24.8%
x264 [info]: mb B  I16..4:  6.2%  0.0%  0.0%  B16..8: 18.0%  0.0%  0.0%  direct: 5.2%  skip:70.6%  L0:48.0% L1:44.2% BI: 7.8%
x264 [info]: final ratefactor: 22.21
x264 [info]: coded y,uvDC,uvAC intra: 25.9% 43.7% 5.4% inter: 6.8% 7.7% 0.1%
x264 [info]: i16 v,h,dc,p: 38% 31% 25%  6%
x264 [info]: i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 34% 24% 16%  4%  5%  5%  4%  5%  4%
x264 [info]: i8c dc,h,v,p: 57% 21% 21%  1%
x264 [info]: Weighted P-Frames: Y:1.7% UV:0.6%
x264 [info]: kb/s:1076.29
encoded 172755 frames, 71.03 fps, 1076.29 kb/s

Start:    12:55:36 PM
End:      1:36:09 PM
Duration: 00:40:33

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
 Encoding video second pass using x264 0.150.2833 8-Bit x64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

C:\Users\Administrator\Desktop\StaxRip-x64-1.5.0.0\Apps\x264\x264.exe --pass 2 --bitrate 1085 --stats "C:\Users\Administrator\Documents\Camtasia Studio\ppp\ppp_temp\ppp.stats" --output "C:\Users\Administrator\Documents\Camtasia Studio\ppp\ppp_temp\ppp_out.h264" "C:\Users\Administrator\Documents\Camtasia Studio\ppp\ppp_temp\ppp.avs"

avs [info]: 1280x544p 0:0 @ 24/1 fps (cfr)
x264 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
x264 [info]: profile High, level 3.1
x264 [info]: frame I:1149  Avg QP:18.17  size: 41880
x264 [info]: frame P:50782 Avg QP:20.78  size: 11018
x264 [info]: frame B:120824 Avg QP:22.96  size:  3048
x264 [info]: consecutive B-frames:  3.9%  5.9%  8.0% 82.3%
x264 [info]: mb I  I16..4: 23.9% 51.0% 25.2%
x264 [info]: mb P  I16..4: 10.9% 22.9%  1.8%  P16..4: 28.3%  8.2%  3.4%  0.0%  0.0%    skip:24.5%
x264 [info]: mb B  I16..4:  1.4%  2.7%  0.1%  B16..8: 32.0%  3.3%  0.4%  direct: 1.4%  skip:58.7%  L0:53.4% L1:43.4% BI: 3.2%
x264 [info]: 8x8 transform intra:63.4% inter:82.1%
x264 [info]: coded y,uvDC,uvAC intra: 42.9% 55.9% 8.9% inter: 9.1% 10.1% 0.1%
x264 [info]: i16 v,h,dc,p: 35% 35% 20% 11%
x264 [info]: i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 27% 21% 29%  3%  4%  5%  4%  4%  3%
x264 [info]: i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 34% 24% 21%  3%  5%  4%  4%  3%  2%
x264 [info]: i8c dc,h,v,p: 56% 21% 21%  2%
x264 [info]: Weighted P-Frames: Y:1.7% UV:0.6%
x264 [info]: ref P L0: 61.9% 12.6% 18.4%  7.0%  0.1%
x264 [info]: ref B L0: 83.9% 13.2%  2.9%
x264 [info]: ref B L1: 96.1%  3.9%
x264 [info]: kb/s:1084.66
encoded 172755 frames, 86.21 fps, 1084.66 kb/s

Start:    1:36:09 PM
End:      2:09:44 PM
Duration: 00:33:34

General
Complete name             : C:\Users\Administrator\Documents\Camtasia Studio\ppp\ppp_temp\ppp_out.h264
Format                    : AVC
Format/Info               : Advanced Video Codec
File size                 : 931 MiB
Writing library           : x264 core 150 r2833 df79067

Video
Format                    : AVC
Format/Info               : Advanced Video Codec
Format profile            : High@L3.1
Format settings, CABAC    : Yes
Format settings, ReFrames : 4 frames
Bit rate                  : 1 085 kb/s
Width                     : 1 280 pixels
Height                    : 544 pixels
Display aspect ratio      : 2.35:1
Frame rate                : 24.000 FPS
Color space               : YUV
Chroma subsampling        : 4:2:0
Bit depth                 : 8 bits
Scan type                 : Progressive
Bits/(Pixel*Frame)        : 0.065
Writing library           : x264 core 150 r2833 df79067

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
          Muxing using MP4Box 0.7.2-DEV-rev37 x64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

C:\Users\Administrator\Desktop\StaxRip-x64-1.5.0.0\Apps\MP4Box\MP4Box.exe -add "C:\Users\Administrator\Documents\Camtasia Studio\ppp\ppp_temp\ppp_out.h264#video" -add "C:\Users\Administrator\Documents\Camtasia Studio\ppp\ppp_temp\ppp ID2_out1.m4a#audio:lang=eng:name=" -itags encoder="StaxRip 1.5.0.0" -new "C:\Users\Administrator\Documents\Camtasia Studio\ppp\ppp.mp4"

[32m[avc-h264] Possible Variable Frame Rate: VUI "fixed_frame_rate_flag" absent.
[0m[32mAVC-H264 import - frame size 1280 x 544 at 24.000 FPS
[32mAVC Import results: 172755 samples (175036 NALUs) - Slices: 1149 I 50782 P 120824 B - 1 SEI - 1140 IDR
[0m[32mStream uses forward prediction - stream CTS offset: 2 frames
[0m[32mIsoMedia import ppp ID2_out1.m4a - track ID 1 - Audio (SR 22050 - 1 channels)

Start:    2:09:44 PM
End:      10:51:25 AM
Duration: 20:41:41

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                         Exception
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

System.ComponentModel.Win32Exception (0x80004005): The resource loader failed to find MUI file
   at StaxRip.Proc.Start() in D:\Projekte\VS\VB\StaxRip\General\Proc.vb:line 208
   at StaxRip.MP4Muxer.Mux() in D:\Projekte\VS\VB\StaxRip\General\Muxer.vb:line 293
   at StaxRip.MainForm.Encode() in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 2192
   at StaxRip.GlobalClass.RunJobRecursive() in D:\Projekte\VS\VB\StaxRip\General\GlobalClass.vb:line 36

**Comment by stax76** [comment]
Can you reproduce it with the newest test build?

https://github.com/stax76/staxrip/blob/master/md/changelog.md

**Comment by el3wdy** [comment]
same problem

[Planet.of.the.Apes.2001.720p.BrRip.x264.YIFY_new_staxrip.txt](https://github.com/stax76/staxrip/files/1168279/Planet.of.the.Apes.2001.720p.BrRip.x264.YIFY_new_staxrip.txt)

**Comment by stax76** [comment]
The last log file is another error, mp4box having a problem with the srt file. The options you have are:

- trying to make the srt file compatible with a software like SubtitleEdit
- report to mp4box support https://github.com/gpac/gpac/issues
- use mkv
