### ISSUE TITLE
Environment Variable %tmp% error

### ISSUE THREAD

**Issue by samkatakouzinos** [stax76/staxrip#240]
Environment variable %tmp% = ```C:\Users\u0001\AppData\Local\Temp``` 
App folder = ```D:\fs\prg\pf\StaxRip\StaxRip-x64-1.6\```

With _Project Options, Paths, Temp Files Directory_
  - Error when = ```%tmp%\staxrip-%source_name%_temp\```
  - Success when = ```C:\Users\u0001\AppData\Local\Temp\staxrip-%source_name%_temp\```

__Sample Log Files__
  
I have included two log files below;

<details><summary>Sample Error Log File 1:</summary><p>

```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                     System Environment
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

StaxRip    : 1.6.0.0
Windows    : Windows 10 Pro 1703
Language   : English (Australia)
CPU        : Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
GPU        : Intel(R) HD Graphics 4000, NVIDIA GeForce GTX 1060 6GB
Resolution : 1024 x 768
DPI        : 96

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                   Source file MediaInfo
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

D:\fs\usrs\pub\vid\mov\AVP Alien vs. Predator (2004)\AVP Alien vs. Predator.avi

General
Complete name                 : D:\fs\usrs\pub\vid\mov\AVP Alien vs. Predator (2004)\AVP Alien vs. Predator.avi
Format                        : AVI
Format/Info                   : Audio Video Interleave
File size                     : 603 MiB
Duration                      : 1 h 41 min
Overall bit rate mode         : Variable
Overall bit rate              : 835 kb/s
Writing application           : VirtualDubMod 1.5.10.2 (build 2540/release)
Writing library               : VirtualDubMod build 2540/release

Video
ID                            : 0
Format                        : MPEG-4 Visual
Format profile                : Advanced Simple@L5
Format, BVOP                  : 2
Format, QPel                  : No
Format, GMC                   : No warppoints
Format, Matrix                : Default (H.263)
Codec ID                      : XVID
Codec ID/Hint                 : XviD
Duration                      : 1 h 41 min
Bit rate                      : 696 kb/s
Width                         : 624 pixels
Height                        : 468 pixels
Display aspect ratio          : 2.40:1
Original display aspect ratio : 4:3
Frame rate                    : 23.976 (24000/1001) FPS
Color space                   : YUV
Chroma subsampling            : 4:2:0
Bit depth                     : 8 bits
Scan type                     : Progressive
Compression mode              : Lossy
Bits/(Pixel*Frame)            : 0.099
Stream size                   : 503 MiB (83%)
Writing library               : XviD 1.2.0.dev47 (UTC 2006-11-01)

Audio
ID                            : 1
Format                        : MPEG Audio
Format version                : Version 1
Format profile                : Layer 3
Mode                          : Joint stereo
Mode extension                : MS Stereo
Codec ID                      : 55
Codec ID/Hint                 : MP3
Duration                      : 1 h 41 min
Bit rate mode                 : Variable
Bit rate                      : 128 kb/s
Channel(s)                    : 2 channels
Sampling rate                 : 48.0 kHz
Compression mode              : Lossy
Stream size                   : 90.9 MiB (15%)
Alignment                     : Aligned on interleaves
Interleave, duration          : 24  ms (0.58 video frame)
Interleave, preload duration  : 128  ms
Writing library               : LAME

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
          Error Demux audio using ffmpeg 3.3.2 x64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

Demux audio using ffmpeg 3.3.2 x64 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
             Demux audio using ffmpeg 3.3.2 x64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

D:\fs\prg\pf\StaxRip\StaxRip-x64-1.6\Apps\ffmpeg\ffmpeg.exe -i "D:\fs\usrs\pub\vid\mov\AVP Alien vs. Predator (2004)\AVP Alien vs. Predator.avi" -vn -sn -y -hide_banner -c:a copy "C:\Users\u0001\AppData\local\temp\staxrip-AVP Alien vs. Predator_temp\AVP Alien vs. Predator ID1.mp3"

Input #0, avi, from 'D:\fs\usrs\pub\vid\mov\AVP Alien vs. Predator (2004)\AVP Alien vs. Predator.avi':
Metadata:
encoder         : VirtualDubMod 1.5.10.2 (build 2540/release)
Duration: 01:41:05.02, start: 0.000000, bitrate: 834 kb/s
Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 624x468 [SAR 1:1 DAR 4:3], 696 kb/s, SAR 117:64 DAR 39:16, 23.98 fps, 23.98 tbr, 23.98 tbn, 23.98 tbc
Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 48000 Hz, stereo, s16p, 125 kb/s
C:\Users\u0001\AppData\local\temp\staxrip-AVP Alien vs. Predator_temp\AVP Alien vs. Predator ID1.mp3: No such file or directory

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
             Demux audio using ffmpeg 3.3.2 x64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

D:\fs\prg\pf\StaxRip\StaxRip-x64-1.6\Apps\ffmpeg\ffmpeg.exe -i "D:\fs\usrs\pub\vid\mov\AVP Alien vs. Predator (2004)\AVP Alien vs. Predator.avi" -vn -sn -y -hide_banner -c:a copy "C:\Users\u0001\AppData\local\temp\staxrip-AVP Alien vs. Predator_temp\AVP Alien vs. Predator ID1.mp3"

Input #0, avi, from 'D:\fs\usrs\pub\vid\mov\AVP Alien vs. Predator (2004)\AVP Alien vs. Predator.avi':
Metadata:
encoder         : VirtualDubMod 1.5.10.2 (build 2540/release)
Duration: 01:41:05.02, start: 0.000000, bitrate: 834 kb/s
Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 624x468 [SAR 1:1 DAR 4:3], 696 kb/s, SAR 117:64 DAR 39:16, 23.98 fps, 23.98 tbr, 23.98 tbn, 23.98 tbc
Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 48000 Hz, stereo, s16p, 125 kb/s
C:\Users\u0001\AppData\local\temp\staxrip-AVP Alien vs. Predator_temp\AVP Alien vs. Predator ID1.mp3: No such file or directory

Start:    12:43:03 AM
End:      12:43:03 AM
Duration: 00:00:00

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                         Exception
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

StaxRip.ErrorAbortException: Demux audio using ffmpeg 3.3.2 x64 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
             Demux audio using ffmpeg 3.3.2 x64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

D:\fs\prg\pf\StaxRip\StaxRip-x64-1.6\Apps\ffmpeg\ffmpeg.exe -i "D:\fs\usrs\pub\vid\mov\AVP Alien vs. Predator (2004)\AVP Alien vs. Predator.avi" -vn -sn -y -hide_banner -c:a copy "C:\Users\u0001\AppData\local\temp\staxrip-AVP Alien vs. Predator_temp\AVP Alien vs. Predator ID1.mp3"

Input #0, avi, from 'D:\fs\usrs\pub\vid\mov\AVP Alien vs. Predator (2004)\AVP Alien vs. Predator.avi':
Metadata:
encoder         : VirtualDubMod 1.5.10.2 (build 2540/release)
Duration: 01:41:05.02, start: 0.000000, bitrate: 834 kb/s
Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 624x468 [SAR 1:1 DAR 4:3], 696 kb/s, SAR 117:64 DAR 39:16, 23.98 fps, 23.98 tbr, 23.98 tbn, 23.98 tbc
Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 48000 Hz, stereo, s16p, 125 kb/s
C:\Users\u0001\AppData\local\temp\staxrip-AVP Alien vs. Predator_temp\AVP Alien vs. Predator ID1.mp3: No such file or directory


   at StaxRip.Proc.Start() in D:\Projekte\VS\VB\StaxRip\General\Proc.vb:line 334
   at StaxRip.ffmpegDemuxer.DemuxAudio(String sourcefile, AudioStream stream, AudioProfile ap, Project proj) in D:\Projekte\VS\VB\StaxRip\General\Demux.vb:line 359
   at StaxRip.ffmpegDemuxer.Run(Project proj) in D:\Projekte\VS\VB\StaxRip\General\Demux.vb:line 309
   at StaxRip.MainForm.Demux() in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 3114
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isNotEncoding) in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 1951
```

</p></details>
<p/>
<details><summary>Sample Error Log File 2:</summary><p>

```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                     System Environment
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

StaxRip    : 1.6.0.0
Windows    : Windows 10 Pro 1703
Language   : English (Australia)
CPU        : Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
GPU        : Intel(R) HD Graphics 4000, NVIDIA GeForce GTX 1060 6GB
Resolution : 1024 x 768
DPI        : 96

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                   Source file MediaInfo
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

D:\fs\usrs\pub\vid\mov\Babe (1995)\Babe (1995).avi

General
Complete name                : D:\fs\usrs\pub\vid\mov\Babe (1995)\Babe (1995).avi
Format                       : AVI
Format/Info                  : Audio Video Interleave
File size                    : 699 MiB
Duration                     : 1 h 32 min
Overall bit rate mode        : Variable
Overall bit rate             : 1 062 kb/s

Video
ID                           : 0
Format                       : MPEG-4 Visual
Format profile               : Advanced Simple@L5
Format, BVOP                 : 2
Format, QPel                 : No
Format, GMC                  : No warppoints
Format, Matrix               : Default (H.263)
Muxing mode                  : Packed bitstream
Codec ID                     : XVID
Codec ID/Hint                : XviD
Duration                     : 1 h 32 min
Bit rate                     : 927 kb/s
Width                        : 640 pixels
Height                       : 336 pixels
Display aspect ratio         : 1.905
Frame rate                   : 23.976 (24000/1001) FPS
Color space                  : YUV
Chroma subsampling           : 4:2:0
Bit depth                    : 8 bits
Scan type                    : Progressive
Compression mode             : Lossy
Bits/(Pixel*Frame)           : 0.180
Stream size                  : 610 MiB (87%)
Writing library              : XviD 1.2.1 (UTC 2008-12-04)

Audio
ID                           : 1
Format                       : MPEG Audio
Format version               : Version 1
Format profile               : Layer 3
Mode                         : Joint stereo
Mode extension               : MS Stereo
Codec ID                     : 55
Codec ID/Hint                : MP3
Duration                     : 1 h 32 min
Bit rate mode                : Variable
Bit rate                     : 122 kb/s
Nominal bit rate             : 128 kb/s
Channel(s)                   : 2 channels
Sampling rate                : 48.0 kHz
Compression mode             : Lossy
Stream size                  : 80.2 MiB (11%)
Alignment                    : Aligned on interleaves
Interleave, duration         : 24  ms (0.58 video frame)
Interleave, preload duration : 151  ms
Writing library              : LAME3.98r

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
          Error Demux audio using ffmpeg 3.3.2 x64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

Demux audio using ffmpeg 3.3.2 x64 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
             Demux audio using ffmpeg 3.3.2 x64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

D:\fs\prg\pf\StaxRip\StaxRip-x64-1.6\Apps\ffmpeg\ffmpeg.exe -i "D:\fs\usrs\pub\vid\mov\Babe (1995)\Babe (1995).avi" -vn -sn -y -hide_banner -c:a copy "C:\Users\u0001\AppData\local\temp\staxrip-Babe (1995)_temp\Babe (1995) ID1.mp3"

Input #0, avi, from 'D:\fs\usrs\pub\vid\mov\Babe (1995)\Babe (1995).avi':
Duration: 01:32:00.43, start: 0.000000, bitrate: 1061 kb/s
Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 640x336 [SAR 1:1 DAR 40:21], 927 kb/s, 23.98 fps, 23.98 tbr, 23.98 tbn, 23.98 tbc
Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 48000 Hz, stereo, s16p, 121 kb/s
C:\Users\u0001\AppData\local\temp\staxrip-Babe (1995)_temp\Babe (1995) ID1.mp3: No such file or directory

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
             Demux audio using ffmpeg 3.3.2 x64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

D:\fs\prg\pf\StaxRip\StaxRip-x64-1.6\Apps\ffmpeg\ffmpeg.exe -i "D:\fs\usrs\pub\vid\mov\Babe (1995)\Babe (1995).avi" -vn -sn -y -hide_banner -c:a copy "C:\Users\u0001\AppData\local\temp\staxrip-Babe (1995)_temp\Babe (1995) ID1.mp3"

Input #0, avi, from 'D:\fs\usrs\pub\vid\mov\Babe (1995)\Babe (1995).avi':
Duration: 01:32:00.43, start: 0.000000, bitrate: 1061 kb/s
Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 640x336 [SAR 1:1 DAR 40:21], 927 kb/s, 23.98 fps, 23.98 tbr, 23.98 tbn, 23.98 tbc
Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 48000 Hz, stereo, s16p, 121 kb/s
C:\Users\u0001\AppData\local\temp\staxrip-Babe (1995)_temp\Babe (1995) ID1.mp3: No such file or directory

Start:    12:49:21 AM
End:      12:49:22 AM
Duration: 00:00:00

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                         Exception
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

StaxRip.ErrorAbortException: Demux audio using ffmpeg 3.3.2 x64 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
             Demux audio using ffmpeg 3.3.2 x64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

D:\fs\prg\pf\StaxRip\StaxRip-x64-1.6\Apps\ffmpeg\ffmpeg.exe -i "D:\fs\usrs\pub\vid\mov\Babe (1995)\Babe (1995).avi" -vn -sn -y -hide_banner -c:a copy "C:\Users\u0001\AppData\local\temp\staxrip-Babe (1995)_temp\Babe (1995) ID1.mp3"

Input #0, avi, from 'D:\fs\usrs\pub\vid\mov\Babe (1995)\Babe (1995).avi':
Duration: 01:32:00.43, start: 0.000000, bitrate: 1061 kb/s
Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 640x336 [SAR 1:1 DAR 40:21], 927 kb/s, 23.98 fps, 23.98 tbr, 23.98 tbn, 23.98 tbc
Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 48000 Hz, stereo, s16p, 121 kb/s
C:\Users\u0001\AppData\local\temp\staxrip-Babe (1995)_temp\Babe (1995) ID1.mp3: No such file or directory


   at StaxRip.Proc.Start() in D:\Projekte\VS\VB\StaxRip\General\Proc.vb:line 334
   at StaxRip.ffmpegDemuxer.DemuxAudio(String sourcefile, AudioStream stream, AudioProfile ap, Project proj) in D:\Projekte\VS\VB\StaxRip\General\Demux.vb:line 359
   at StaxRip.ffmpegDemuxer.Run(Project proj) in D:\Projekte\VS\VB\StaxRip\General\Demux.vb:line 309
   at StaxRip.MainForm.Demux() in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 3114
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isNotEncoding) in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 1951
```

</p></details>

**Comment by samkatakouzinos** [comment]
Found ```D:\fs\prg\pf\StaxRip\StaxRip-x64-1.6\%tmp%``` with subfolders and log files. 
- ```D:\fs\prg\pf\StaxRip\StaxRip-x64-1.6\%tmp%\staxrip-AVP Alien vs. Predator_temp```
  - ```AVP Alien vs. Predator_staxrip.log```
- ```D:\fs\prg\pf\StaxRip\StaxRip-x64-1.6\%tmp%\staxrip-Babe (1995)_temp```
  - ```Babe (1995)_staxrip.log```

**Comment by stax76** [comment]
I've looked at the code and there was a casing problem, you can try using upper case %TMP%. I've modified the code to make it case insensitive but I've not tested the code, I hope it will work in the next build.

**Comment by stax76** [comment]
I've uploaded a test build, maybe you can confirm that it's fixed.

https://github.com/stax76/staxrip/blob/master/md/changelog.md

**Comment by samkatakouzinos** [comment]
Build: StaxRip-x64-1.6.0.1-test
Works with lowercase %tmp%

**Comment by stax76** [comment]
Fine, thanks for reporting and testing.
