### ISSUE TITLE
Error Muxing using MP4Box 0.7.2-DEV-rev79 x64

### ISSUE THREAD

**Issue by bank000539** [stax76/staxrip#249]
Can You Help Me?

------------------------------------------------------------------------------------------------

Error Muxing using MP4Box 0.7.2-DEV-rev79 x64

Muxing using MP4Box 0.7.2-DEV-rev79 x64 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
          Muxing using MP4Box 0.7.2-DEV-rev79 x64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

C:\Users\Aibill\Desktop\staxrip_n\Apps\MP4Box\MP4Box.exe -fps 0.000022 -add C:\Users\Aibill\Desktop\satchan_v2_temp\satchan_v2_new_out.h264#video -add "C:\Users\Aibill\Desktop\satchan_v2_temp\satchan_v2 ID1 English_a1.m4a#audio:lang=eng:name=" -add "C:\Users\Aibill\Desktop\satchan_v2_temp\satchan_v2 ID1 English_a1_a2.m4a#audio:lang=eng:name=" -itags encoder="StaxRip 1.6.0.0" -new C:\Users\Aibill\Desktop\satchan_v2_new.mp4

AVC-H264 import - frame size 1920 x 1080 at 0.000 FPS
Error importing C:\Users\Aibill\Desktop\satchan_v2_temp\satchan_v2_new_out.h264#video: Invalid IsoMedia File

StaxRip.ErrorAbortException: Muxing using MP4Box 0.7.2-DEV-rev79 x64 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
          Muxing using MP4Box 0.7.2-DEV-rev79 x64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

C:\Users\Aibill\Desktop\staxrip_n\Apps\MP4Box\MP4Box.exe -fps 0.000022 -add C:\Users\Aibill\Desktop\satchan_v2_temp\satchan_v2_new_out.h264#video -add "C:\Users\Aibill\Desktop\satchan_v2_temp\satchan_v2 ID1 English_a1.m4a#audio:lang=eng:name=" -add "C:\Users\Aibill\Desktop\satchan_v2_temp\satchan_v2 ID1 English_a1_a2.m4a#audio:lang=eng:name=" -itags encoder="StaxRip 1.6.0.0" -new C:\Users\Aibill\Desktop\satchan_v2_new.mp4

AVC-H264 import - frame size 1920 x 1080 at 0.000 FPS
Error importing C:\Users\Aibill\Desktop\satchan_v2_temp\satchan_v2_new_out.h264#video: Invalid IsoMedia File

   at StaxRip.Proc.Start() in D:\Projekte\VS\VB\StaxRip\General\Proc.vb:line 334
   at StaxRip.MP4Muxer.Mux() in D:\Projekte\VS\VB\StaxRip\General\Muxer.vb:line 294
   at StaxRip.GlobalClass.ProcessJob() in D:\Projekte\VS\VB\StaxRip\General\GlobalClass.vb:line 142

**Comment by stax76** [comment]
It says Invalid IsoMedia File to the h264 file. Which video encoder was used to encode it? Can you play the h264 file in your media player? What shows MediaInfo for the h264 file?

**Comment by bank000539** [comment]
video encoder => AAC

Sorry, I don't have h264 file. But normally I'll use VLC media player.

**Comment by stax76** [comment]
Please post the complete log file.
