### ISSUE TITLE
Error when trying to add files to queue/joblist in latest unstable

### ISSUE THREAD

**Issue by Fencat** [stax76/staxrip#262]
Updated to 1.6.0.4 and suddenly getting an error when trying to add files using the batch tool for x265.

My copy of stax is located at "D:\StaxRip-x64" and the error indicates its looking for something in "D:\Projekte" that doesnt exist.

Downgrading to 1.6.0.3 it behaves as expected again.

`-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                     System Environment
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

StaxRip    : 1.6.0.4
Windows    : Windows 7 Professional
Language   : Swedish (Sweden)
CPU        : Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
GPU        : VNC Mirror Driver, NVIDIA GeForce GTX 980
Resolution : 2560 x 1440
DPI        : 96

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                         Exception
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

System.NullReferenceException: Object reference not set to an instance of an object.
   at StaxRip.ProcController.Finished() in D:\Projekte\VS\VB\StaxRip\General\ProcController.vb:line 205
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isNotEncoding) in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 2185
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files) in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 1753
   at StaxRip.MainForm.OpenVideoSourceFile(String fp) in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 1749
   at StaxRip.MainForm.ShowOpenSourceDialog() in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 4942
   at StaxRip.MainForm.lTip_Click() in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 5166
   at StaxRip.MainForm._Lambda$__R132-13(Object a0, EventArgs a1)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by stax76** [comment]
The paths are the source code files, new build should be online in 1-2 minutes.

**Comment by Fencat** [comment]
1.6.0.5 is working as expected again, thank you very much for the quick fix!
