### ISSUE TITLE
Error when adding 20+ files with batch mode latest test build.

### ISSUE THREAD

**Issue by Fencat** [stax76/staxrip#263]
Seems to hit a limit at around 20 files, trying to add more then that and I get the following error.

Have not had any problems with this at 1.6.0.3 and below.

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                     System Environment
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

StaxRip    : 1.6.0.5
Windows    : Windows 7 Professional
Language   : Swedish (Sweden)
CPU        : Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
GPU        : VNC Mirror Driver, NVIDIA GeForce GTX 980
Resolution : 2560 x 1440
DPI        : 96

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                         Exception
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

System.OutOfMemoryException: Out of memory.
   at System.Drawing.Graphics.FromHdcInternal(IntPtr hdc)
   at System.Drawing.Font.GetHeight()
   at System.Drawing.Font.get_Height()
   at StaxRip.UI.MenuItemEx.GetPreferredSize(Size constrainingSize) in D:\Projekte\VS\VB\StaxRip\UI\Menu Types.vb:line 321
   at System.Windows.Forms.Layout.FlowLayout.VerticalElementProxy.GetPreferredSize(Size proposedSize)
   at System.Windows.Forms.Layout.FlowLayout.xLayoutRow(ContainerProxy containerProxy, ElementProxy elementProxy, Int32 startIndex, Int32 endIndex, Rectangle rowBounds, Int32& breakIndex, Boolean measureOnly)
   at System.Windows.Forms.Layout.FlowLayout.xLayout(IArrangedElement container, Rectangle displayRect, Boolean measureOnly)
   at System.Windows.Forms.Layout.FlowLayout.LayoutCore(IArrangedElement container, LayoutEventArgs args)
   at System.Windows.Forms.Layout.LayoutEngine.Layout(Object container, LayoutEventArgs layoutEventArgs)
   at System.Windows.Forms.Control.OnLayout(LayoutEventArgs levent)
   at System.Windows.Forms.ToolStrip.OnLayout(LayoutEventArgs e)
   at System.Windows.Forms.ToolStripDropDownMenu.OnLayout(LayoutEventArgs e)
   at System.Windows.Forms.Control.PerformLayout(LayoutEventArgs args)
   at System.Windows.Forms.ToolStrip.DoLayoutIfHandleCreated(ToolStripItemEventArgs e)
   at System.Windows.Forms.ToolStrip.OnItemAdded(ToolStripItemEventArgs e)
   at System.Windows.Forms.ToolStripItemCollection.Add(ToolStripItem value)
   at StaxRip.UI.ActionMenuItem.Add(ToolStripItemCollection items, String path, Action action, Symbol symbol, String tip) in D:\Projekte\VS\VB\StaxRip\UI\Menu Types.vb:line 584
   at StaxRip.UI.ActionMenuItem.Add(ToolStripItemCollection items, String path, Action action) in D:\Projekte\VS\VB\StaxRip\UI\Menu Types.vb:line 545
   at StaxRip.UI.ContextMenuStripEx.Add(String path, Action action, String help, Boolean enabled) in D:\Projekte\VS\VB\StaxRip\UI\Menu Types.vb:line 703
   at StaxRip.UI.ContextMenuStripEx.Add(String path, Action action, String help) in D:\Projekte\VS\VB\StaxRip\UI\Menu Types.vb:line 695
   at StaxRip.FiltersListView.BuildMenu() in D:\Projekte\VS\VB\StaxRip\Controls\FiltersListView.vb:line 96
   at StaxRip.MainForm.OpenProject(String path, Boolean saveCurrent) in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 1653
   at StaxRip.MainForm.ShowOpenSourceDialog() in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 4940
   at StaxRip.MainForm.lTip_Click() in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 5165
   at StaxRip.MainForm._Lambda$__R132-13(Object a0, EventArgs a1)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by stax76** [comment]
For every file added to batch processing a project is loaded and what is new is that every time a project loads the filters menu is rebuild and that is where the crash occurs, unfortunately I don't know why it crashes, there seem to be a resource limit exceeded and at this point I don't know what to do against it. I could however add 100 files without crash. Do you have many filter profiles added? This could be a explanation. Something similar was reported before 3 times with +200 files.

**Comment by Fencat** [comment]
The only filters in the list are the default ones and only ones ticked are manual source and resize. Other then that it's just x265 settings.

Have tried a few times with different files and if I try adding more then 20 it crashes. It does however add the first 20 files to the queue before crashing if that's significant in any way. 

Is there any other info or log I can get you?

**Comment by Fencat** [comment]
Can't seem to edit my post on mobile sorry...

Filters in lust are 
Source
Crop
Field
Noise
Resize 

Active ones are only source manual and resize bicubic

Only have remote access with mobile today I'm afraid but I'll try a completely new clean install tomorrow to rule out anything I might have done.

**Comment by Fencat** [comment]
Can't seem to edit my post on mobile sorry...

Filters in list are
Source
Crop
Field
Noise
Resize

Active ones are only source manual and resize bicubic

Only have remote access with mobile today I'm afraid but I'll try a completely new clean install tomorrow to rule out anything I might have done.

**Comment by Fencat** [comment]
Clean copy of latest 1.6.0.6 with all default settings, nothing touched except adding 22 files with batch.

It adds the first 20 files then crashes with the same error.
https://pastebin.com/dR7XCtAH

And the debug.log file looks like this
https://pastebin.com/4T0Z3Wsu

**Comment by stax76** [comment]
I'm currently rewriting batch processing which hopefully will fix this. A first run with 300 files added and encoded succeeded.

**Comment by Fencat** [comment]
Thank you for looking into it and please let me know if I can give you any other useful information or test something.

**Comment by stax76** [comment]
Ok, I hope this will work:

https://forum.doom9.org/showthread.php?p=1814897#post1814897

**Comment by Fencat** [comment]
Only had time for some quick tests this morning but so far so good, could add 30 files without problem.

I'll do some more extensive testing tomorrow and report back then but looks like its working well and also alot faster then before so great work and thank you!

**Comment by Fencat** [comment]
Tested with up to 190 files and all seems to be working great so as far as I can find this bug is squished.
And as a bonus as said above noticeably faster then before so great work!

Thank you very much!
