### ISSUE TITLE
mkv err

### ISSUE THREAD

**Issue by ramyatt** [stax76/staxrip#336]
Error Indexing using ffmsindex (1.7.0.0)

Indexing using ffmsindex failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

----------------------- Indexing using ffmsindex -----------------------

C:\Users\ROMYO\Downloads\Compressed\StaxRip-x64-1.7.0.0-stable\Apps\Plugins\both\ffms2\ffmsindex.exe "F:\ramy 2\Video\vlips\New folder\New folder\(6)  Mere Rashke Qamar Tu Ne Pehli Nazar Nusrat Fateh Ali Khan - By Junaid Asghar - YouTube.MKV" "F:\ramy 2\Video\vlips\New folder\New folder\(6)  Mere Rashk..._temp\(6)  Mere Rashke Qamar Tu Ne Pehli Nazar Nusrat Fateh Ali Khan - By Junaid Asghar - YouTube.ffindex"

Indexing error: Invalid initial pts, dts, and duration

StaxRip.ErrorAbortException: Indexing using ffmsindex failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

----------------------- Indexing using ffmsindex -----------------------

C:\Users\ROMYO\Downloads\Compressed\StaxRip-x64-1.7.0.0-stable\Apps\Plugins\both\ffms2\ffmsindex.exe "F:\ramy 2\Video\vlips\New folder\New folder\(6)  Mere Rashke Qamar Tu Ne Pehli Nazar Nusrat Fateh Ali Khan - By Junaid Asghar - YouTube.MKV" "F:\ramy 2\Video\vlips\New folder\New folder\(6)  Mere Rashk..._temp\(6)  Mere Rashke Qamar Tu Ne Pehli Nazar Nusrat Fateh Ali Khan - By Junaid Asghar - YouTube.ffindex"

Indexing error: Invalid initial pts, dts, and duration

   at StaxRip.Proc.Start() in D:\Projekte\VS\VB\StaxRip\General\Proc.vb:line 338
   at StaxRip.GlobalClass.ffmsindex(String sourcePath, String cachePath, Boolean indexAudio, Project proj) in D:\Projekte\VS\VB\StaxRip\General\GlobalClass.vb:line 631
   at StaxRip.MainForm.Indexing() in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 3167
   at StaxRip.VideoScript.Synchronize(Boolean convertToRGB, Boolean comparePath) in D:\Projekte\VS\VB\StaxRip\General\VideoScript.vb:line 193
   at StaxRip.VideoScript.GetFramerate() in D:\Projekte\VS\VB\StaxRip\General\VideoScript.vb:line 393
   at StaxRip.MainForm.ModifyFilters() in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 2265
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding) in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 1981

**Comment by jalba69** [comment]
Hi, 

I'm not sure what the exact problem is but you can try to rename your video so it use a less longer name, i had issues with very long names for the tittles of my videos; try to rename your video before adding it to Staxrip and see if it helps.
