### ISSUE TITLE
staxrip 1.7.0.0 crashes ffmpeg

### ISSUE THREAD

**Issue by scottydog90** [stax76/staxrip#339]
Error ffmpeg: Re-mux TS to MKV using ffmpeg 3.3.3 (1.7.0.0)

ffmpeg: Re-mux TS to MKV using ffmpeg 3.3.3 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

------------- ffmpeg: Re-mux TS to MKV using ffmpeg 3.3.3 -------------

"C:\Staxrip 1700\Apps\ffmpeg\ffmpeg.exe" -i "C:\Users\Scott\Videos\Strike Back 6 Episode 5.ts" -c:a copy -c:v copy -sn -y -hide_banner "C:\Users\Scott\Videos\Strike Back 6 Episode 5_temp\Strike Back 6 Episode 5.mkv"

Input #0, mpegts, from 'C:\Users\Scott\Videos\Strike Back 6 Episode 5.ts':
Duration: 00:45:19.14, start: 0.200000, bitrate: 13859 kb/s
Program 1
Stream #0:0[0x1011]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], 25.17 fps, 50 tbr, 90k tbn, 50 tbc
Stream #0:1[0x1100](eng): Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, stereo, fltp, 384 kb/s
Output #0, matroska, to 'C:\Users\Scott\Videos\Strike Back 6 Episode 5_temp\Strike Back 6 Episode 5.mkv':
Metadata:
encoder         : Lavf57.71.100
Stream #0:0: Video: h264 (Main) (H264 / 0x34363248), yuv420p(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 25.17 fps, 50 tbr, 1k tbn, 90k tbc
Stream #0:1(eng): Audio: ac3 ([0] [0][0] / 0x2000), 48000 Hz, stereo, fltp, 384 kb/s
Stream mapping:
Stream #0:0 -> #0:0 (copy)
Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[matroska @ 00000000050e0560] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[matroska @ 00000000050e0560] Can't write packet with unknown timestamp
av_interleaved_write_frame(): Invalid argument
video:53kB audio:3kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

StaxRip.ErrorAbortException: ffmpeg: Re-mux TS to MKV using ffmpeg 3.3.3 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

------------- ffmpeg: Re-mux TS to MKV using ffmpeg 3.3.3 -------------

"C:\Staxrip 1700\Apps\ffmpeg\ffmpeg.exe" -i "C:\Users\Scott\Videos\Strike Back 6 Episode 5.ts" -c:a copy -c:v copy -sn -y -hide_banner "C:\Users\Scott\Videos\Strike Back 6 Episode 5_temp\Strike Back 6 Episode 5.mkv"

Input #0, mpegts, from 'C:\Users\Scott\Videos\Strike Back 6 Episode 5.ts':
Duration: 00:45:19.14, start: 0.200000, bitrate: 13859 kb/s
Program 1
Stream #0:0[0x1011]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], 25.17 fps, 50 tbr, 90k tbn, 50 tbc
Stream #0:1[0x1100](eng): Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, stereo, fltp, 384 kb/s
Output #0, matroska, to 'C:\Users\Scott\Videos\Strike Back 6 Episode 5_temp\Strike Back 6 Episode 5.mkv':
Metadata:
encoder         : Lavf57.71.100
Stream #0:0: Video: h264 (Main) (H264 / 0x34363248), yuv420p(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 25.17 fps, 50 tbr, 1k tbn, 90k tbc
Stream #0:1(eng): Audio: ac3 ([0] [0][0] / 0x2000), 48000 Hz, stereo, fltp, 384 kb/s
Stream mapping:
Stream #0:0 -> #0:0 (copy)
Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[matroska @ 00000000050e0560] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[matroska @ 00000000050e0560] Can't write packet with unknown timestamp
av_interleaved_write_frame(): Invalid argument
video:53kB audio:3kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

   at StaxRip.Proc.Start() in D:\Projekte\VS\VB\StaxRip\General\Proc.vb:line 338
   at StaxRip.CommandLineDemuxer.Run(Project proj) in D:\Projekte\VS\VB\StaxRip\General\Demux.vb:line 207
   at StaxRip.MainForm.Demux() in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 3119
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding) in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 1962

**Comment by yolanjoy** [comment]
Similar issue I encountered with the same version.  Is there any fix?

**Comment by scottydog90** [comment]
Nobody has ever responded, so problem still the same/unresolved. 😟

**Comment by Matze2019** [comment]
In 1.7.6 unstable the problem is still present.
