### ISSUE TITLE
Encoder output file is missing (1.7.0.0)

### ISSUE THREAD

**Issue by YinnVI** [stax76/staxrip#354]
How to fix this?
```
Encoder output file is missing (1.7.0.0)

C:\Users\Yosia Kefas\Desktop\New folder\[animeindo.vide..._temp\[animeindo.video]brtt_-_41__[1080p]_(1)-1_new_out.hevc

StaxRip.ErrorAbortException: C:\Users\Yosia Kefas\Desktop\New folder\[animeindo.vide..._temp\[animeindo.video]brtt_-_41__[1080p]_(1)-1_new_out.hevc
   at StaxRip.VideoEncoder.AfterEncoding() in D:\Projekte\VS\VB\StaxRip\Encoding\VideoEncoder.vb:line 108
   at StaxRip.QSVEnc.Encode() in D:\Projekte\VS\VB\StaxRip\Encoding\QSVEnc.vb:line 85
   at StaxRip.GlobalClass.ProcessVideo() in D:\Projekte\VS\VB\StaxRip\General\GlobalClass.vb:line 225
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Projekte\VS\VB\StaxRip\General\GlobalClass.vb:line 137
```

**Comment by stax76** [comment]
Please try the last build 1.7.0.5 and post the full log file.
