### ISSUE TITLE
Crash at the end of encoding

### ISSUE THREAD

**Issue by Helenerineium** [stax76/staxrip#358]
-------------------------- System Environment --------------------------

StaxRip    : 1.7.0.5
Windows    : Windows 10 Education Insider Preview 1709
Language   : English (United States)
CPU        : Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
GPU        : Intel(R) HD Graphics 630, NVIDIA GeForce GTX 1050
Resolution : 3840 x 2160
DPI        : 240

------------------------------ Exception ------------------------------

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'TextBox'.
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.TextBoxBase.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.PointToScreen(Point p)
   at System.Windows.Forms.TextBoxBase.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Not really a big issue, can't reproduce it...

**Comment by stax76** [comment]
The stack trace don't show file and line so I can't do anything unless it's reproducible.
