### ISSUE TITLE
nvidia gt5x960 failed with exit code: 1 (0x1)

### ISSUE THREAD

**Issue by leinad23ec** [stax76/staxrip#382]
Hello, 

About a year ago, I posted how Handbrake takes too long to encode in x265. 
http://www.tomsguide.com/answers/id-3051134/handbrake-hevc-h265-encoding-blu-ray-hours.html
I stopped my attempts to use handbrake with an nvidia card, after learning that Handbrake does not support Hardware x265 encoding. The last answer I got, was to try StaxRIP, since it supports x265 encoding with Nvidia cards. Now I started trying Stax Rip, but every time, it comes out with an error code(ATTACHED):

[nvidia 265 error.txt](https://github.com/stax76/staxrip/files/1865881/nvidia.265.error.txt)

Having zero experience in StaxRip, I followed the settings from a youtube video for nvidia 10bit gpu encoding. And I thought that maybe those settings were the issue. So I selected"Automatic Workflow", loaded the Bluray folder, and the error is the same.

Can someone explain me what am I missing?

Stats:
Windows 10 home 64bits
AMD FX(tm)-4130 Quad-core Processor
Ram: 16gb
Video Card:
EVGA GeForce GTX 960 Super Clocked ACX 2.0 4GB GDDR5 128 Bit Gaming Graphic Card (04G-P4-3962-KR) 

Thank you

**Comment by leinad23ec** [comment]
bump?

**Comment by p9535422** [comment]
Were you attempting to encode using NVIDIA H.265 (NVEnc)? NVENC HEVC Main10 10-bit hardware encoding is only supported on NVIDIA Pascal GP10x. Not supported on NVIDIA Maxwell.

Navigate to the NVEnc folder (\Apps\NVEnc), run the command _NVEncC64.exe --check-features_

You will notice the the output
_10bit depth               no_

Refer to 
https://en.wikipedia.org/wiki/Nvidia_NVENC#Fourth_Generation_.28Pascal_GP10x.29

**Comment by leinad23ec** [comment]
Well yes, I was trying.
I found some topics about the "Maxwell limitations", but I also found a number of people talking about encoding with hardware on a nvidia 900 series. So I thought it was possible. 

Well if it is not, then my apologies and thank you for your answer.

**Comment by p9535422** [comment]
I've been using NVIDIA NVENC to re-encode my video collections on GTX960. Just not on 10 bit.

**Comment by leinad23ec** [comment]
Well yes, I was trying.
I found some topics about the "Maxwell limitations", but I also found a number of people talking about encoding with hardware on a nvidia 900 series. So I thought it was possible. 

Well if it is not, then my apologies and thank you for your answer.

**Comment by leinad23ec** [comment]
Interesting, 

I got the same error, even when I set it up to 8 bit.

Any ideas?

**Comment by leinad23ec** [comment]
Same error exists, even when trying 8 bit.
I have changed the container to h264, x264, nvidia 264, x265, h265, nvidia 265.
Also the container, from THD+ac3, to ac3, ma4, etc.

It always "Analyzes" and then the error.

Any ideas?

"

Error Demux M2TS using eac3to 3.31 x86

Demux M2TS using eac3to 3.31 x86 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
              Demux M2TS using eac3to 3.31 x86
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

"G:\WIN10\USERS\Daniel\Libraries\Downloads\staxrip 1.6\Apps\eac3to\eac3to.exe" "G:\WIN10\USERS\Daniel\Libraries\Videos\Movie\BDMV\PLAYLIST\" 1) 2: G:\WIN10\USERS\Daniel\Libraries\Videos\Movie\Movie.mkv 3: "G:\WIN10\USERS\Daniel\Libraries\Videos\Movie\Movie ID3 English.thd+ac3" 1: "G:\WIN10\USERS\Daniel\Libraries\Videos\Movie_chapters.txt" 6: "G:\WIN10\USERS\Daniel\Libraries\Videos\Movie\Movie ID6 English.sup" -progressnumbers

M2TS, 1 video track, 3 audio tracks, 1 subtitle track, 2:43:48, 24p /1.001
1: Chapters, 16 chapters
2: h264/AVC, 1080p24 /1.001 (16:9)
3: TrueHD/AC3 (Atmos), English, 7.1 channels, 48kHz
(embedded: AC3 EX, 5.1 channels, 448kbps, 48kHz, dialnorm: -27dB)
4: DTS Master Audio, English, 5.1 channels, 24 bits, 48kHz
(core: DTS, 5.1 channels, 1509kbps, 48kHz)
5: AC3, English, 5.1 channels, 640kbps, 48kHz, dialnorm: -27dB
6: Subtitle (PGS), English
Creating file "G:\WIN10\USERS\Daniel\Libraries\Videos\Movie_chapters.txt"...
v02 Extracting video track number 2...
a03 Extracting audio track number 3...
a03 Removing AC3 dialog normalization...
The h264 muxer doesn't support this stream type yet.v02
Please send a 20MB sample to dear@madshi.netv02
s06 Extracting subtitle track number 6...
v02 Muxing video to Matroska...
Aborted at file position 1048576.



StaxRip.ErrorAbortException: Demux M2TS using eac3to 3.31 x86 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
              Demux M2TS using eac3to 3.31 x86
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

"G:\WIN10\USERS\Daniel\Libraries\Downloads\staxrip 1.6\Apps\eac3to\eac3to.exe" "G:\WIN10\USERS\Daniel\Libraries\Videos\Movie\BDMV\PLAYLIST\" 1) 2: G:\WIN10\USERS\Daniel\Libraries\Videos\Movie\Movie.mkv 3: "G:\WIN10\USERS\Daniel\Libraries\Videos\Movie\Movie ID3 English.thd+ac3" 1: "G:\WIN10\USERS\Daniel\Libraries\Videos\Movie_chapters.txt" 6: "G:\WIN10\USERS\Daniel\Libraries\Videos\Movie\Movie ID6 English.sup" -progressnumbers

M2TS, 1 video track, 3 audio tracks, 1 subtitle track, 2:43:48, 24p /1.001
1: Chapters, 16 chapters
2: h264/AVC, 1080p24 /1.001 (16:9)
3: TrueHD/AC3 (Atmos), English, 7.1 channels, 48kHz
(embedded: AC3 EX, 5.1 channels, 448kbps, 48kHz, dialnorm: -27dB)
4: DTS Master Audio, English, 5.1 channels, 24 bits, 48kHz
(core: DTS, 5.1 channels, 1509kbps, 48kHz)
5: AC3, English, 5.1 channels, 640kbps, 48kHz, dialnorm: -27dB
6: Subtitle (PGS), English
Creating file "G:\WIN10\USERS\Daniel\Libraries\Videos\Movie_chapters.txt"...
v02 Extracting video track number 2...
a03 Extracting audio track number 3...
a03 Removing AC3 dialog normalization...
The h264 muxer doesn't support this stream type yet.v02
Please send a 20MB sample to dear@madshi.netv02
s06 Extracting subtitle track number 6...
v02 Muxing video to Matroska...
Aborted at file position 1048576.


   at StaxRip.Proc.Start() in D:\Projekte\VS\VB\StaxRip\General\Proc.vb:line 334
   at StaxRip.MainForm.OpenEac3toDemuxForm(String playlistFolder, Int32 playlistID) in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 5046


"

Thank you


Thank you

**Comment by pwacooijmans** [comment]
The thing you CAN try however is to try and encode h265 with EVERY setting set to rec709....in theory there shouldn't be anything wrong with that. But I can't try it myself to check if that might work.

**Comment by pwacooijmans** [comment]
ALSO DON'T forget to set the master-display string to rec709.
