### ISSUE TITLE
H.265/HEVC isn't supported by the graphics card.

### ISSUE THREAD

**Issue by wolfhowling** [stax76/staxrip#388]
I am getting this error this error every time i try to convert a movie. This started happening since i change my CPU to Ryzen 2 2700x, all the rest is the same using a GTX1080, the same saved profile as before even windows is the same all drivers up to date and the only graphic card enabled is the GTX 1080 the only thing that change was the system board and cpu but i keep getting the error below. My entire system functions as before except staxrip.

Was weirder is it references a D: drive which is non existent in my system.

Any Ideas?

NVEnc Error (1.7.0.0)

H.265/HEVC isn't supported by the graphics card.

StaxRip.ErrorAbortException: H.265/HEVC isn't supported by the graphics card.
   at StaxRip.NVEnc.Encode() in D:\Projekte\VS\VB\StaxRip\Encoding\NVEnc.vb:line 72
   at StaxRip.GlobalClass.ProcessVideo() in D:\Projekte\VS\VB\StaxRip\General\GlobalClass.vb:line 225
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Projekte\VS\VB\StaxRip\General\GlobalClass.vb:line 137

Another thing i forgot is this is my first attempt to convert a video since updating windows 10 to the April Creator, not sure if that may have been the actual cause. I tested build 1.7.0.6 and the same error persist.

**Comment by wolfhowling** [comment]
After further investigation it is a NVEncC64 issue. I have posted the issue on their site.

[https://github.com/rigaya/NVEnc/issues/48](https://github.com/rigaya/NVEnc/issues/48)
