### ISSUE TITLE
Error at Open Some Media

### ISSUE THREAD

**Issue by alirezavafakhah** [stax76/staxrip#396]
Hi

This Error show when file add to StaxRip

Error Demux audio using MP4Box 0.7.2-DEV-rev79 (1.7.0.0)

Demux audio using MP4Box 0.7.2-DEV-rev79 failed with exit code: -1073741819 (0xC0000005)

The exit code might be a system error code: The instruction at 0xp referenced memory at 0xp. The memory could not be s.

--------------- Demux audio using MP4Box 0.7.2-DEV-rev79 ---------------

C:\Users\AVF\Downloads\Compressed\StaxRip-x64-1.7.0.0-stable\Apps\MP4Box\MP4Box.exe -single 2 -out "C:\Users\AVF\Desktop\۲۰۱۶۰۴۰۷_۱۶۵۵۴۱_temp\۲۰۱۶۰۴۰۷_۱۶۵۵۴۱ ID1 English SoundHandle.m4a" C:\Users\AVF\Desktop\۲۰۱۶۰۴۰۷_۱۶۵۵۴۱.mp4

[iso file] Unknown box type SDLN
[iso file] Unknown box type smrd
[iso file] Unknown box type smta
[AVC/HEVC] Not enough bits in bitstream !!
[AVC/HEVC] Not enough bits in bitstream !!
[AVC/HEVC] Not enough bits in bitstream !!
[AVC/HEVC] Not enough bits in bitstream !!
[AVC/HEVC] Not enough bits in bitstream !!
[AVC/HEVC] Not enough bits in bitstream !!
[AVC/HEVC] Not enough bits in bitstream !!
[AVC/HEVC] Not enough bits in bitstream !!
[Core] system failure for file opening of \gpac_0000728e_2 in mode w+b: 0x00000005

StaxRip.ErrorAbortException: Demux audio using MP4Box 0.7.2-DEV-rev79 failed with exit code: -1073741819 (0xC0000005)

The exit code might be a system error code: The instruction at 0xp referenced memory at 0xp. The memory could not be s.

--------------- Demux audio using MP4Box 0.7.2-DEV-rev79 ---------------

C:\Users\AVF\Downloads\Compressed\StaxRip-x64-1.7.0.0-stable\Apps\MP4Box\MP4Box.exe -single 2 -out "C:\Users\AVF\Desktop\۲۰۱۶۰۴۰۷_۱۶۵۵۴۱_temp\۲۰۱۶۰۴۰۷_۱۶۵۵۴۱ ID1 English SoundHandle.m4a" C:\Users\AVF\Desktop\۲۰۱۶۰۴۰۷_۱۶۵۵۴۱.mp4

[iso file] Unknown box type SDLN
[iso file] Unknown box type smrd
[iso file] Unknown box type smta
[AVC/HEVC] Not enough bits in bitstream !!
[AVC/HEVC] Not enough bits in bitstream !!
[AVC/HEVC] Not enough bits in bitstream !!
[AVC/HEVC] Not enough bits in bitstream !!
[AVC/HEVC] Not enough bits in bitstream !!
[AVC/HEVC] Not enough bits in bitstream !!
[AVC/HEVC] Not enough bits in bitstream !!
[AVC/HEVC] Not enough bits in bitstream !!
[Core] system failure for file opening of \gpac_0000728e_2 in mode w+b: 0x00000005

   at StaxRip.Proc.Start() in D:\Projekte\VS\VB\StaxRip\General\Proc.vb:line 338
   at StaxRip.MP4BoxDemuxer.Demux(String sourcefile, AudioStream stream, AudioProfile ap, Project proj) in D:\Projekte\VS\VB\StaxRip\General\Demux.vb:line 601
   at StaxRip.MP4BoxDemuxer.Run(Project proj) in D:\Projekte\VS\VB\StaxRip\General\Demux.vb:line 471
   at StaxRip.MainForm.Demux() in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 3119
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding) in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 1962

**Comment by Revan654** [comment]
It's likely the file was originally encoded incorrectly. What is Mediainfo reporting?

MP4ToolBox is having problems figuring out the Codec ID. Which usually only happens when there something wrong with the video it self.

You could try to using ffmpeg on the mp4 to demux the file to see if that works or not.

**Comment by Revan654** [comment]
I would check file with the other encoder to see if everything is correctly. It's possible that sections of the video is missing or audio is out of sync. 

Mediainfo is very good at reading the different formats. If it can't read then you know something is wrong.

Demux (Tools -> Settings -> Preprocessing) Then add process with ffmpeg for mp4 and move it to the top.

**Comment by alirezavafakhah** [comment]
Thanks
Convert Good but after time in video Audio lost

MediaInfo:
General
Complete name                            : C:\Users\AVF\Desktop\۲۰۱۶۰۴۰۷_۱۶۵۵۴۱.mp4
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42 (isom/mp42)
File size                                : 202 MiB
Duration                                 : 1 min 38 s
Overall bit rate                         : 17.3 Mb/s
Encoded date                             : UTC 2016-04-07 12:27:24
Tagged date                              : UTC 2016-04-07 12:27:24

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 1 Ref Frames
Format settings, CABAC                   : Yes
Format settings, RefFrames               : 1 frame
Format settings, GOP                     : M=1, N=30
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 1 min 38 s
Source duration                          : 1 min 38 s
Bit rate                                 : 17.0 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Rotation                                 : 90°
Frame rate mode                          : Variable
Frame rate                               : 30.000 FPS
Minimum frame rate                       : 19.991 FPS
Maximum frame rate                       : 30.602 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.273
Stream size                              : 199 MiB (98%)
Source stream size                       : 199 MiB (98%)
Title                                    : VideoHandle
Language                                 : English
Encoded date                             : UTC 2016-04-07 12:27:24
Tagged date                              : UTC 2016-04-07 12:27:24
mdhd_Duration                            : 98087

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : mp4a-40-2
Duration                                 : 1 min 38 s
Bit rate mode                            : Constant
Bit rate                                 : 12.0 Gb/s
Nominal bit rate                         : 256 kb/s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 137 GiB
Title                                    : SoundHandle
Language                                 : English
Encoded date                             : UTC 2016-04-07 12:27:24
Tagged date                              : UTC 2016-04-07 12:27:24
