### ISSUE TITLE
Program crash when using copy command in filter->preview

### ISSUE THREAD

**Issue by gundamftw** [stax76/staxrip#402]
When go to option->filters->click on the box->preview, then right click->copy everything, the program will crash.

**Comment by Revan654** [comment]
try updating your runtimes.

It's a little hard to debug the error without a log.

**Comment by gundamftw** [comment]
This is the error message:

`
System.ArgumentNullException: Value cannot be null.
Parameter name: text
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at StaxRip.UI.RichTextBoxEx._Lambda$__7-1()
   at StaxRip.UI.ActionMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by Revan654** [comment]
It's expecting text it never receives the text.
It looks like whatever is being added it causing problems.

Try:
add the text after the source inside the editor and see if it crashes. That way we can rule out if the filters are causing the problems are not.

Also go into the app list and make sure MS runtimes are all listed. Also make sure you have all the fonts installed too.

This is my own personal version of StaxRip, which I have tested heavily. I have zero crashes with it. If the same errors happen with this version. It's something to do with your PC. It's missing or file got corrupted some how.

link: https://github.com/Revan654/staxrip
