### ISSUE TITLE
Crash at Adding Job to Queue (Next button)

### ISSUE THREAD

**Issue by JoyBell2** [stax76/staxrip#410]
`------------------------------ Exception ------------------------------

System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at StaxRip.TaskDialog`1.Show()
   at StaxRip.MainForm.bnSkip_Click()
   at StaxRip.MainForm._Lambda$__R20-5(Object a0, EventArgs a1)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`

Been happing a bunch lately on different computers. Happens when I have an encode all set up and I want to add it to the Jobs with the Next button.

Windows 10, 1803
Stax 1.8.2.0
Multiple computers: Ryzen 7 2700, Intel i7 7700k, Intel 6700T, Intel 7700HQ

**Comment by Revan654** [comment]
That Code is for the Following Issue:

> The user does not have remote access to the computer through DCOM. Typically, DCOM errors occur when connecting to a remote computer with a different operating system version.

MS added some additional Security locks & checks with some of there recent updates. which could be what your running into.

**Comment by JoyBell2** [comment]
Local computer internal drive, same drive as Staxrip, different folder.
Still getting issue.

**Comment by Revan654** [comment]
That is tied to Permission. It looks like it doesn't have proper Permission and an error is kicked back. I know MS added a bunch of stupid locks in the last update. Which could be a reason your getting the errors.

I updated some of the services for the next build, Which should help avoiding the issue.

Also I would upgrade your dotnet Framework to latest build.

**Comment by JoyBell2** [comment]
It seems to happen almost every time  after opening a job to make an edit.

**Comment by Revan654** [comment]
I would check your Filters, Throughout the latest testing the only time I had System.UnauthorizedAccessException: Access is denied was when one of the dlls created a crash due to there compatibility It was designed for different System. Some dlls have multi versions due to Advanced Vector Extensions(AVX). Make sure your using the correct one. by default AVX are the default in package I released. Which should work on any system. Then some of the dlls are designed for AVS 2.5. Which could create some issues when using AVS+.

Have you tried to use VapourSynth and see if the problems happened?

**Comment by JoyBell2** [comment]
None of my customer filters are set up in VapourSynth. So I haven't tried it.

**Comment by Revan654** [comment]
DLL files Must be Linked in the App Manager. Version 1.9 is Now out.

**Comment by JoyBell2** [comment]
I think it might be due to running stax from the Download folder where I unzipped the folder. More security in Windows folders.

**Comment by Revan654** [comment]
> 
> 
> I think it might be due to running stax from the Downloads folder where I unzipped the folder. More security in Windows folders.

If your using a admin account, Download shouldn't have that much security compared to Program Files Folder. 

I also disable all UAC in Windows.
