### ISSUE TITLE
StaxRip  long path / file names triggers unhandled exception

### ISSUE THREAD

**Issue by Dave--G** [stax76/staxrip#98]
Using batch source, staxrip encountered a long filename and crashed:

Exception

Could not find a part of the path 'C:\Program Files (x86)\StaxRip\StaxRip-x64-1.3.8.7-test\%source_dir%_StaxTemp\%source_name%_temp_NVEncC.bat'.

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files (x86)\StaxRip\StaxRip-x64-1.3.8.7-test\%source_dir%_StaxTemp\%source_name%_temp_NVEncC.bat'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at StaxRip.Proc.WriteBatchFile(String path, String content) in D:\Projekte\VS\VB\StaxRip\General\Proc.vb:line 59
   at StaxRip.NVIDIAEncoder.Encode() in D:\Projekte\VS\VB\StaxRip\Encoding\NVIDIAEncoder.vb:line 72
   at StaxRip.MainForm.Encode() in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 2220
   at StaxRip.MainForm.RunJobRecursive() in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 3462

**Comment by stax76** [comment]
I don't remember if I made improvements meanwhile, if it happens again please reopen the issue and post a full log file.
